dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
dotenv: .env
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
networks:
  default: development
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}